$(function () {
    // var texts = [
    //     'Where there is no hope, there is no struggle.',
    //     'No one can disappoint you, except yourself.',
    //     'Discipline yourself, don\'t manage others.',
    //     'Time has wings.',
    //     'To make the crown, don\'t waste every day.',
    //     'There is no bad thing, only a bad mood.',
    //     'Is not worse than others, but not enough to pay.',
    //     'Tell yourself everyday: I\'m really good.',
    //     'All things come to those who wait.',
    //     'Tomorrow never comes.',
    //     'A person showing off what the heart is missing.',
    //     'Aim at the top of the mountain, mountain scenery is not greed.',
    //     'Lie on the bed, do not feel the warmth of the sun.',
    //     'While there is life there is hope.',
    //     'Nothing is impossible!',
    //     'The secret of success is to stick to your goals and beliefs.',
    //     'There is no one to do, only those who do not do things.',
    //     'If we have accepted the worst, there is no loss.',
    //     'Sow nothing, reap nothing.',
    //     'True, sincere to also, not fine not sincere, not moving.',
    //     'With the positive people together, can let us be in a high mood.',
    //     'You should thank every person who let you change the way it is.',
    //     'When the sky is dark to a certain extent, the stars will shine.',
    //     'Studies this matter, lacks the time, but is lacks diligently.',
    //     'Do one thing at a time, and do well.',
    //     'There is no garden without its weeds.',
    //     'Have a dream to chase, no dream of the people, the soul is empty.',
    //     'To serve the people, in fact, is to pay the rent on the earth.',
    //     'Everyone has at least one dream, there is a reason to be strong.',
    //     'Time will tell.',
    //     'Nurture passes nature.',
    // ];
    var texts = [
        '本是青灯不归客， 却因浊酒留风尘',
        '一万年太久，只争朝夕',
        '愿我如星君如月，夜夜流光相皎洁',
        '山中何事？松花酿酒，春水煎茶',
        '日暮酒醒人已远，满天风雨下西楼',
        '当时明月在，曾照彩云归',
        '荷风送香气，竹露滴清响',
        '鹿门月照开烟树，忽到庞公栖隐处',
        '庭院深深深几许，杨柳堆烟，帘幕无重数',
        '小楼一夜听春雨，深巷明朝卖杏花',
        '醉后不知天在水，满船清梦压星河',
        '老来多健忘，唯不忘相思',
        '黄河落天走东海，万里写入胸怀间',
        '男儿何不带吴钩，收取关山五十州',
        '我本楚狂人，凤歌笑孔丘',
        '任他红尘滚滚，我自清风明月',
        '我自横刀向天笑，去留肝胆两昆仑',
        '五花马，千金裘，呼儿将出换美酒，与尔同消万古愁',
        '竹杖芒鞋轻似马，谁怕？一蓑烟雨任平生',
        '海棠未雨，梨花先雪，一半春休',
        '我有一瓢酒，可以慰风尘',
        '世间草木皆美，人不是。中药很苦，你也是',
        '惊觉相思不露，原来只因已入骨',
        '情不知所起，一往而深',
        '酴釄落尽，犹赖有梨花',
        '欲买桂花同载酒，终不似、少年游',
        '梨花院落溶溶月，柳絮池塘淡淡风',
        '海水梦悠悠，君愁我亦愁。 南风知我意，吹梦到西洲',
        '流水落花春去也，天上人间',
        '帘外雨潺潺，春意阑珊',
        '应是天仙狂醉，乱把白云揉碎',
    ];
    var myDate = new Date;
    var date = myDate.getDate();
    var text = texts[date - 1];
    $("#home_p").html(text)
})
